import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const font = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Better Authy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning className={`${font.className} antialiased`}
      >
        {children}
        <Toaster position='top-center' richColors />
      </body>
    </html>
  );
}
